apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-trackmate-message-producer
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: kaniko-trackmate-message-producer
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: [
          "--dockerfile=/godata/pipelines/trackmate-message-producer/Dockerfile",
          "--context=/godata/pipelines/trackmate-message-producer",
          "--destination=quay.io/14west/trackmate-message-producer:dev"
        ]
        volumeMounts:
        - mountPath: /godata
          name: gocdagent-data
        - mountPath: /kaniko/.docker/config.json
          name: docker-creds
          subPath: config.json
        env:
        - name: DESITINATION
        value: quay.io/14west/trackmate-message-producer:dev
      restartPolicy: Never   
      volumes:
      - name: gocdagent-data
        persistentVolumeClaim:
          claimName: gocdagent-node-and-go
      - name: docker-creds
        configMap:
          defaultMode: 420
          name: configcontent
      backoffLimit: 1
